### PR TITLE
Update bagit.py

### PR DESCRIPTION
**Pull request by finoradin**
Fixing validation bug - oxum validation was outside the if fast condition, so validation was *always* defaulting to fast

### CODE REVIEW

**Comment by finoradin** [comment]
Related issue: https://github.com/LibraryOfCongress/bagit-python/issues/177

**Comment by acdha** [comment]
Can you give a little more detail about the scenario you encountered? We always want to validate the payload oxum value even if we're not doing a fast validation so the code appears to be correct and a brief review of the existing tests shows at least one test which relies on slow validation.

**Comment by finoradin** [comment]
If I intentionally modified a file in a bag, and validated, it would only complain about the payload oxum, but would not report anything regarding checksum validation failure - i.e. which file failed, etc. I thought it was just stopping at the oxum check, thus not validating the checksums. If I was wrong and it is actually still validating the checksums, I would expect it to report back accordingly of course.

**Comment by acdha** [comment]
The proposed new logic doesn't change the fast processing and it appears to introduce a bug where the non-fast mode would no longer validate the oxum check. We always need to do that, the only thing fast mode does is bail out immediately if that fails rather than checksumming a bunch of files first.

I'm getting the impression that there might be a different workflow that you have in mind, and that makes me wonder whether the answer would be a different CLI flag.

**Comment by finoradin** [comment]
Yes, the proposed changes were not intended to impact the fast processing. the issue, at least, as far as I could tell was that the fast processing was happening even when it wasn’t asked to happen.

Regular validation was only reporting failed oxum and, not showing any output about individual file validation, nor indicating, which of the files had failed.

**Comment by acdha** [comment]
> Yes, the proposed changes were not intended to impact the fast processing. the issue, at least, as far as I could tell was that the fast processing was happening even when it wasn’t asked to happen.

That's expected - the fast processing isn't separate, it's only doing the first half of the validation process (see [section 3 of RC 8493](https://datatracker.ietf.org/doc/html/rfc8493#autoid-17)) but both steps are required.

It would definitely make sense to extend the output to be more precise if there are cases where we're not telling you which files are inconsistent with the metadata.

**Comment by finoradin** [comment]
Ok well in that case feel free to reject this PR since it sounds like it should be doing "fast" validation (checking the oxum) _and_ validating the payload checksums (whereas I think here it only does the latter). We can continue discussing here: https://github.com/LibraryOfCongress/bagit-python/issues/177

**Pull request closed without merging**
