### PR TITLE
Build universal wheels

### PR DESCRIPTION
**Pull request by nsoranzo**
See https://packaging.python.org/guides/distributing-packages-using-setuptools/#universal-wheels

### CODE REVIEW

**Comment by acdha** [comment]
I'm really inclined to drop Python 2.6 support since it's been deprecated by the core Python development team since 2013. I'll merge this PR but we should update the docs as well.

**Comment by johnscancella** [comment]
@acdha I have yet to be on a system that required me to use python 2.6(and you know we work on some old kernels). Any reason to not drop it now?

**Comment by nsoranzo** [comment]
@acdha Thanks for the merge!

That's need anyway to support Python 2.7 and 3.x with the same wheel.

**Comment by acdha** [comment]
See https://github.com/LibraryOfCongress/bagit-python/pull/110 for the Python 2.6 removal.

**Comment by nsoranzo** [comment]
Also, it could be pretty cool if you could provide wheels on PyPI for the next releases!

**Comment by acdha** [comment]
Will do!

**Comment by acdha** [comment]
https://pypi.org/project/bagit/ has 1.7.0 with wheels. Since it dropped Python 2.6 support I figured it was more than a point release.

**Comment by nsoranzo** [comment]
Thanks a lot!

**Pull request merged**
