### PR TITLE
Use logger and with statements, don't use sys.exit

### PR DESCRIPTION
**Pull request by Hwesta**
A few small changes:
* Changed to use the bagit logger, instead of the root logger (`logger.foo` vs `logging.foo`)
* Removed `sys.exit` calls, since that will exit Python and is problematic in a library
* Converted file opens to use the `with` statement, which automatically closes files
* Reraise exceptions with `raise` to preserve tracebacks

### CODE REVIEW

**Comment by Hwesta** [comment]
Switched it to raise a `BagError` instead of returning None, since that's more consistent with other behavior.

**Comment by edsu** [comment]
Thanks for the TLC :-) unfortunately I can't merge PRs anymore. But I trust someone at LC will.

**Comment by dbrunton** [comment]
It looks great, and the build passes. Does this change anything wrt the version of Python required, or anything else we should note in the README?

**Comment by acdha** [comment]
The with statement was added in Python 2.5 which is already below the minimum supported version (2.6).

**Comment by Hwesta** [comment]
Not that I can think of.  As noted above, the `with` statement was my main concern and it's pre-2.6. I can't find when re-raising was added, so I assume it's early enough (and all the builds pass).

**Comment by dbrunton** [comment]
Awesome, thanks a lot @Hwesta and @edsu !

**Comment by acdha** [comment]
:+1: from me

**Comment by edsu** [comment]
:cake:

**Pull request merged**
